server:
  name: "axum-server-template"
  port: 8000
  address: "127.0.0.1"

database:
  # url: "postgresql://root:123456@localhost:5432/database"
  url: "postgresql://root:123456@10.0.0.204:12001/database"

redis:
  # url: "redis://127.0.0.1/"
  url: "redis://10.0.0.204:12002/"

logger:
  level: "debug"

auth:
  secret: "123456"
  access_token_duration: 15 # 分钟
  refresh_token_duration: 30 # 天数

email:
  username: "xx@xx.xx"
  password: "xx"
  secure: "tls"
  host: "xx"
  port: 465
